# Generated by Django 5.2.2 on 2025-06-08 05:23

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0004_alter_portfolioprofile_about_title_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="project_images/"
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("description", ckeditor.fields.RichTextField()),
                ("demo_link", models.URLField(blank=True, null=True)),
                ("source_code", models.URLField(blank=True, null=True)),
                (
                    "tech_stacks",
                    models.ManyToManyField(
                        blank=True, related_name="projects", to="core.techstack"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectKeyFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("short_description", models.TextField()),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="key_features",
                        to="projects.project",
                    ),
                ),
            ],
        ),
    ]
