# Generated by Django 5.2.2 on 2025-06-08 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="featuted",
            field=models.BooleanField(default=False),
        ),
    ]
