# Generated by Django 5.2.2 on 2025-06-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_rename_featuted_project_featured"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectkeyfeature",
            name="short_description",
            field=models.CharField(max_length=255),
        ),
    ]
