# Generated by Django 5.2.2 on 2025-06-13 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_alter_projectkeyfeature_short_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="slug",
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
