# Generated by Django 5.2.2 on 2025-06-07 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PortfolioProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=255, null=True)),
                ("job_title", models.CharField(blank=True, max_length=255, null=True)),
                ("headline", models.CharField(blank=True, max_length=255, null=True)),
                ("short_bio", models.TextField(blank=True, null=True)),
                (
                    "about_title",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("about_description", models.TextField(blank=True, null=True)),
                (
                    "resume",
                    models.FileField(blank=True, null=True, upload_to="resumes/"),
                ),
                ("github_profile_link", models.URLField(blank=True, null=True)),
                ("linkedin_profile_link", models.URLField(blank=True, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                "verbose_name": "Portfolio Profile",
                "verbose_name_plural": "Portfolio Profile",
            },
        ),
        migrations.CreateModel(
            name="TechStackCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="TechStack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("image", models.URLField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tech_stacks",
                        to="core.techstackcategory",
                    ),
                ),
            ],
        ),
    ]
