# Generated by Django 5.2.2 on 2025-06-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="portfolioprofile",
            name="short_bio",
        ),
        migrations.AlterField(
            model_name="portfolioprofile",
            name="headline",
            field=models.TextField(blank=True, null=True),
        ),
    ]
