# Generated by Django 5.2.2 on 2025-06-07 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_portfolioprofile_short_bio_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="techstackcategory",
            options={
                "verbose_name": "Tech Stack Category",
                "verbose_name_plural": "Tech Stack Categories",
            },
        ),
        migrations.RenameField(
            model_name="techstack",
            old_name="image",
            new_name="image_url",
        ),
    ]
