# Generated by Django 5.2.2 on 2025-06-07 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_techstackcategory_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolioprofile",
            name="about_title",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="portfolioprofile",
            name="full_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="portfolioprofile",
            name="job_title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name="WorkExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("company_name", models.CharField(max_length=150)),
                ("role", models.CharField(max_length=150)),
                ("location", models.CharField(max_length=150)),
                (
                    "tech_stacks",
                    models.ManyToManyField(blank=True, to="core.techstack"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkExperienceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                (
                    "work_experience",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.workexperience",
                    ),
                ),
            ],
        ),
    ]
